// 邀请事件
export const ReferralEventType = {
  UPDATE_BASICS: 'REFERRAL_UPDATE_BASICS',
  UPDATE_INVITE: 'REFERRAL_UPDATE_INVITE',
  UPDATE_OVERVIEW: 'REFERRAL_UPDATE_OVERVIEW',
  UPDATE_CHANNEL: 'REFERRAL_UPDATE_CHANNEL',
  GET_CHANNEL: 'REFERRAL_GET_CHANNEL',
};
